const vehiclesTypes = {
    ADD_NEW_VEHICLE_START: 'ADD_NEW_VEHICLE_START',
    FETCH_VEHICLES_START: 'FETCH_VEHICLES_START',
    SET_VEHICLES: 'SET_VEHICLES',
    DELECTE_VEHICLE_START: 'DELECTE_VEHICLE_START'
}

export default vehiclesTypes;