const vehiclesTypes = {
    ADD_VEHICLE_START: 'ADD_VEHICLE_START',
    SET_INVENTORY_STATS: 'SET_INVENTORY_STATS',
    FETCH_VEHICLES_START: 'FETCH_VEHICLES_START',
    SET_VEHICLES: 'SET_VEHICLES',
    DELETE_VEHICLE_START: 'DELETE_VEHICLE_START'
}

export default vehiclesTypes;